### ISSUE TITLE
Embed Google Doc (App Tutorial) to WebAppTutorial.html

### ISSUE THREAD

**Issue by Titane73** [Titane73/it115-a5-g2-app#6]
I suggest using [embedresponsively.com](url) to create embedded page for the site. If not familiar, it will produce an iframe and CSS.  Copy and paste into the html and CSS, respectively. 

It's likely the page will not fit as desired.  Adjust the width and min-height to adjust.

**Comment by tacostreets** [comment]
Great! I'll assign this tomorrow once we get an idea on progress.

**Comment by tacostreets** [comment]
I am closing this and creating a new issue for the final embed and page update
