### ISSUE TITLE
Embed Google Doc (Stack Tutorial) to meantutorial.html

### ISSUE THREAD

**Issue by Titane73** [Titane73/it115-a5-g2-app#7]
I suggest using embedresponsively.com to create embedded page for the site. If not familiar, it will produce an iframe and CSS. Copy and paste into the html and CSS, respectively.

It's likely the page will not fit as desired. Adjust the width and min-height to adjust.

**Comment by tacostreets** [comment]
Thanks, Ti. On it!

**Comment by tacostreets** [comment]
This is done. I will close this and make a new issue for the final embed and page update
